### ISSUE TITLE
Implement css sample 8

### ISSUE THREAD

**Issue by mailtodanish** [mailtodanish/CSS-Samples#5]
Implement below

![CPT2210071056-833x205](https://user-images.githubusercontent.com/7193460/194474867-8e926269-8827-4bbc-b13c-a18825c94ef0.gif)

**Comment by kirtiraj22** [comment]
hey @mailtodanish i can make it. 
can you assign it to me?

**Comment by mailtodanish** [comment]
please refer previous samples

**Comment by kirtiraj22** [comment]
okk!

**Comment by mailtodanish** [comment]
@kirtiraj22 please update main readme.md
